registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
go-server:
  image: go-server
  hostname: go-server
  ports:
    - '8153:8153'
    - '8154:8154'
go-agent:
    image: go-agent
    links:
      - go-server